spring:
  datasource:
    url: jdbc:h2:mem:finDb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      #ddl-auto: validate
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql

# SpringDoc OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
    filter: true
    displayRequestDuration: true
    defaultModelsExpandDepth: 2
    defaultModelExpandDepth: 2
  show-actuator: false
  group-configs:
    - group: 'users'
      display-name: 'User Management APIs'
      paths-to-match: /v1/users/**
    - group: 'incomes'
      display-name: 'Income Management APIs'
      paths-to-match: /v1/incomes/**
    - group: 'expenses'
      display-name: 'Expense Management APIs'
      paths-to-match: /v1/expenses/**
    - group: 'categories'
      display-name: 'Category Management APIs'
      paths-to-match: /v1/categories/**

# Server configuration
server:
  port: 8080

# Logging configuration for API documentation
logging:
  level:
    org.springdoc: DEBUG
    io.swagger: DEBUG